### ISSUE TITLE
there is no SftpAdapter class

### ISSUE THREAD

**Issue by ahmad-saad** [shopwareLabs/SwagMediaSftp#2]
Class 'League\Flysystem\Sftp\SftpAdapter' not found 

I have this error message when I try to visit my homepage

**Comment by bcremer** [comment]
Please note that you have to install the dependencies via `composer install` first:

```
curl -sS https://getcomposer.org/installer | php
php composer.phar install
```

**Comment by ahmad-saad** [comment]
thank's
